version: "3.9"
services:
  inference:
    command: ["bash", "run.sh"]
    image: "cs-ai.tencentcloudcr.com/triton/codegeex:dep1"
    volumes:
      - /root/.cache:/root/.cache
      - /root/wangrui:/app
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]